language: python
sudo: false
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
install:
- python setup.py develop
- pip install nose
script: nosetests -w tests
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: VWY03BMoD51ffI668jJ077xlVXGy/mW+vua1ZNs6tK5S6pDjTvl41GRHgtZiBu/bRcmTYPUEeOroSgbFpoCLEWEK4JiVGaN4h/OoELPo2UBWcx3bpYe1Rlj1yqrflMvfLCu6a8cCSb2AQd4W9B36DcnUCxZnJsq7EDzterscjbc=
  on:
    tags: true
    repo: vmalloc/sentinels
